/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Actividad2;

/**
 *
 * @author johan
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    
    // Mi kami El constructor PantallaPrincipal inicializa los componentes de la interfaz gráfica llamando al 
    // método initComponents(). El segundo constructor.
    public PantallaPrincipal() {
        initComponents();
    }
   
    
    // El segundo constructor, que recibe parámetros PantallaSecundaria y boolean, 
    // lanza una excepción indicando que la operación no está soportada, porque aún no se ha 
    // implementado el metodo initComponents(); .
    PantallaPrincipal(PantallaSecundaria aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaPrincipalButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PantallaPrincipalTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PantallaPrincipalButton1.setText("enviar");
        PantallaPrincipalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaPrincipalButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(PantallaPrincipalTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PantallaPrincipalButton1)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PantallaPrincipalButton1)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Mi kami Este método se ejecuta cuando se realiza una acción (como un clic) en un botón en la 
    //PantallaPrincipal. El método obtiene el texto ingresado en un JTextPane, crea una instancia 
    //de PantallaSecundaria con ese texto, y hace visible la nueva pantalla.
    private void PantallaPrincipalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaPrincipalButton1ActionPerformed
        // TODO add your handling code here:
        String texto = PantallaPrincipalTextPane.getText();
        PantallaSecundaria secundaria = new PantallaSecundaria(this, true, "Hola " + texto);
        secundaria.setVisible(true);
    }//GEN-LAST:event_PantallaPrincipalButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Mi kami El método main es el punto de entrada de la aplicación Java. Este método configura la apariencia
    // de la interfaz gráfica utilizando el "look and feel" Nimbus, y luego crea y muestra la ventana 
    // principal de la aplicación (PantallaPrincipal).
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PantallaPrincipalButton1;
    private javax.swing.JTextPane PantallaPrincipalTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
